### PR TITLE
Uses multipart upload for big uploads

### LINKED ISSUE #12: Multipart Uploads for Large Files
When uploading a large directory of text files (27G uncompressed, 8G compressed), I get an error. I'm guessing we need to use the [S3 MultiPart Upload API](http://docs.aws.amazon.com/AmazonS3/latest/dev/uploadobjusingmpu.html)?

```
$ java -jar ~/local/bin/DatastoreCLI.jar upload -p pubmed-central/ -g org.allenai.corpora.pubmedcentral -n PubmedCentral -v 1 -d private
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: Your proposed upload exceeds the maximum allowed size (Service: Amazon S3; Status Code: 400; Error Code: EntityTooLarge; Request ID: C538693739F3B6AD), S3 Extended Request ID: hC5wVmtuUfI7LSJHhxoPW8C3REerq1KsdBTrrQ3Ubqn4S2IwbuUbVxamvIS64uq0
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:937)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:273)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3660)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1432)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1289)
	at org.allenai.datastore.Datastore.publish(Datastore.scala:491)
	at org.allenai.datastore.cli.UploadApp$$anonfun$7.apply(UploadApp.scala:52)
	at org.allenai.datastore.cli.UploadApp$$anonfun$7.apply(UploadApp.scala:45)
	at scala.Option.foreach(Option.scala:257)
	at org.allenai.datastore.cli.UploadApp$.delayedEndpoint$org$allenai$datastore$cli$UploadApp$1(UploadApp.scala:45)
	at org.allenai.datastore.cli.UploadApp$delayedInit$body.apply(UploadApp.scala:7)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.allenai.datastore.cli.UploadApp$.main(UploadApp.scala:7)
	at org.allenai.datastore.cli.DatastoreCli$.delayedEndpoint$org$allenai$datastore$cli$DatastoreCli$1(DatastoreCli.scala:7)
	at org.allenai.datastore.cli.DatastoreCli$delayedInit$body.apply(DatastoreCli.scala:3)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.allenai.datastore.cli.DatastoreCli$.main(DatastoreCli.scala:3)
	at org.allenai.datastore.cli.DatastoreCli.main(DatastoreCli.scala)
```

### PR DESCRIPTION
**Pull request by dirkgr**
This uses multipart uploads for uploading datastore files. It may or may not give a speed bonus, but more importantly it lets us upload files larger than 5GB.

While I was at it, I also added log messages that show during the upload.

Fixes #12.

@jkinkead, can you take a look?

### CODE REVIEW

**Comment by dirkgr** [comment]
@afader reported the original bug, so FYI

File: datastore/src/main/scala/org/allenai/datastore/Datastore.scala [hunk 1]
```diff
@@ -1,12 +1,14 @@
 package org.allenai.datastore
 
+import com.amazonaws.event.{ ProgressEvent, ProgressListener }
```
Comment (jkinkead) [inline datastore/src/main/scala/org/allenai/datastore/Datastore.scala]: Should be moved below to the other `com.amazonaws` imports.

File: datastore/src/main/scala/org/allenai/datastore/Datastore.scala [hunk 2]
```diff
@@ -382,6 +384,31 @@ class Datastore(val name: String, val s3: AmazonS3Client) extends Logging {
...
+    try {
+      val request = new PutObjectRequest(bucketName, locator.s3key, path.toFile)
+      request.setGeneralProgressListener(new ProgressListener {
+        private var lastLogMessage = System.currentTimeMillis()
+
+        override def progressChanged(progressEvent: ProgressEvent): Unit = {
+          val now = System.currentTimeMillis()
+          if (now - lastLogMessage >= 1000) {
+            logger.info(
+              s"Uploading $path to the $name datastore. " +
```
Comment (jkinkead) [inline datastore/src/main/scala/org/allenai/datastore/Datastore.scala]: Seems like you could log this at the start, and just log the progress in the listener. Not sure how long path part of this message is, though.

File: datastore/src/main/scala/org/allenai/datastore/Datastore.scala [hunk 3]
```diff
@@ -382,6 +384,31 @@ class Datastore(val name: String, val s3: AmazonS3Client) extends Logging {
   // Putting data into the datastore
   //
 
+  private def multipartUpload(path: Path, locator: Locator): Unit = {
+    val tm = new TransferManager(s3)
+    try {
+      val request = new PutObjectRequest(bucketName, locator.s3key, path.toFile)
+      request.setGeneralProgressListener(new ProgressListener {
+        private var lastLogMessage = System.currentTimeMillis()
```
Comment (jkinkead) [inline datastore/src/main/scala/org/allenai/datastore/Datastore.scala]: Should you initialize to `System.currentTimeMillis() - 1000`, so that you get an initial log message right away?

File: datastore/src/main/scala/org/allenai/datastore/Datastore.scala (hunk 2 above)
Comment (dirkgr) [inline datastore/src/main/scala/org/allenai/datastore/Datastore.scala]: When the upload is small, I don't want it to print anything. Same as the download.

File: datastore/src/main/scala/org/allenai/datastore/Datastore.scala (hunk 3 above)
Comment (dirkgr) [inline datastore/src/main/scala/org/allenai/datastore/Datastore.scala]: No, see above.

File: datastore/src/main/scala/org/allenai/datastore/Datastore.scala (hunk 1 above)
Comment (dirkgr) [inline datastore/src/main/scala/org/allenai/datastore/Datastore.scala]: Hrm. I thought IntelliJ would do this for me. I just auto-organized all the imports in the project. Maybe it'll do it once it can start from a clean state.
